org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=mobstackeradv
mod_name=Mob Stacker Advanced
mod_version=0.0.5
mod_group_id=com.proxwian.mobstackeradv
mod_authors=proxwian
mod_license=MIT
mod_description=Configurable mob stacking for Minecraft 1.21.1.

minecraft_version=1.21.1
neo_version=21.1.229
fabric_loader_version=0.17.3
fabric_api_version=0.116.11+1.21.1

forge_minecraft_version=1.20.1
forge_version=47.2.0
