pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
    }
}

rootProject.name = 'mobstackeradv'

include 'forge'

if (JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_21)) {
    include 'neoforge'
    include 'fabric'
} else {
    println 'Skipping NeoForge/Fabric modules because Minecraft 1.21.1 requires Gradle to run on Java 21.'
}
